apiVersion: v1
kind: Namespace
metadata:
  name: microapps
  labels:
    app.kubernetes.io/part-of: microapps-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microapps
  namespace: microapps
